apps:
  - cwd: ./ #
    min_uptime: 10000 
    max_restarts: 3
    name: KazuhaBot
    script: ./config/pm2/pm2-run.js 
    error_file: ./pm2/error.log
    out_file: ./pm2/out.log
    log_date_format: 'YYYY-MM-DD HH:mm Z'
    max_memory_restart: 512M
    cron_restart: '0 8 * * *'